
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class AdminGetDetails extends javax.swing.JFrame {

    /**
     * Creates new form AdminGetDetails
     */
    ArrayList<Cart> al;
    public  AdminGetDetails(ArrayList<Cart> al) {
        initComponents();
        this.al = al;
        setSize(1000,650);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Fill Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 50, 250, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Customer Phone Number :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 200, 300, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Mode Of Payment :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 320, 270, 50);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Do Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 460, 230, 60);

        tf1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(570, 200, 300, 40);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "UPI", "Mobile Banking", "Credit Card", "DebitCard" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 320, 300, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String phone = tf1.getText();
        String paymenttype = (String) jComboBox1.getSelectedItem();
        String email = Global.adminemail;
        int grandTotal = Global.grandTotal;
        int billid = 0;
        try{
            ResultSet rs = dbloader.executeQuery("Select * from bill");
            rs.moveToInsertRow();
            rs.updateInt("gtotal",grandTotal);
            rs.updateString("phoneno",phone);
            rs.updateString("adminemail",email);
            rs.updateString("paymenttype", paymenttype);
            rs.insertRow();
            
           ResultSet rs2 = dbloader.executeQuery("select MAX(billid) as billid from bill ");
            if (rs2.next()) {
                billid = rs2.getInt("billid");
            }
            ResultSet rs3 = dbloader.executeQuery("Select * from billdetail");
            
            for(int i =0;i< al.size();i++)
            {
                rs3.moveToInsertRow();
                
                rs3.updateInt("billid",billid);
                rs3.updateString("pname",al.get(i).productname);
                rs3.updateInt("offerprice",al.get(i).offerprice );
                rs3.updateInt("quantity", al.get(i).quantity);
                rs3.insertRow();
            }
            JOptionPane.showMessageDialog(this, "Bill Generated Successfully");
            
            dispose();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) { 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGetDetails(al).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
